//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Borne.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_CHECKCURSOR                 101
#define IDD_TEST_VIEW                   102
#define IDC_RADIOCURSOR                 103
#define IDD_BORNE_FORM                  104
#define IDP_SOCKETS_INIT_FAILED         105
#define IDC_MULTILINEEDITCURSOR         106
#define IDC_COMBOCURSOR                 107
#define IDC_GROUPCURSOR                 108
#define IDC_LABELCURSOR                 109
#define IDC_EDITCURSOR                  110
#define IDC_DATECURSOR                  111
#define IDR_MAINFRAME                   112
#define IDR_BORNETYPE                   113
#define IDB_RATP                        114
#define IDR_DYNCONTROLBAR               115
#define IDB_FLECHE_BN                   116
#define IDB_BITMAP2                     117
#define IDI_CONTACT                     118
#define IDB_SPLASH                      119
#define IDD_TEST_FORM                   120
#define IDD_DIALOG2                     121
#define IDR_CONTEXT                     122
#define IDB_FRANCECARD                  123
#define IDB_ABTOF                       124
#define IDB_DICE                        125
#define IDB_BANNER                      126
#define IDB_FLECHE_NB                   127
#define IDD_SETTINGS                    144
#define IDB_VET                         145
#define IDB_KEYDOT                      152
#define IDB_KEY0                        153
#define IDB_KEY1                        154
#define IDB_KEY2                        155
#define IDB_KEY3                        156
#define IDB_KEY4                        157
#define IDB_KEY5                        158
#define IDB_KEY6                        159
#define IDB_KEY7                        160
#define IDB_KEY8                        161
#define IDB_KEY9                        162
#define IDB_RATP1                       163
#define IDB_SPLASH1                     164
#define IDD_DYNPROP_PAGE1               332
#define IDD_DYNPROP_PAGE2               335
#define IDD_DYNPROP_PAGE3               336
#define IDD_COPTIONTREEDEMO_DIALOG      338
#define IDR_XUICONTROLBAR               339
#define IDC_CURSOR1                     340
#define IDD_PPG_GENERAL                 341
#define IDB_IMAGES_NORMAL               342
#define IDC_LIST_CTRL                   343
#define IDR_EDITORTOOLBAR               344
#define IDC_TABORDER                    1000
#define IDC_TEXT                        1001
#define IDC_LABEL1                      1002
#define IDC_EDIT_DB                     1002
#define IDC_ORDINAL                     1003
#define IDC_CLOCK                       1004
#define IDC_COMBO_TYPEBORNE             1004
#define IDC_RADIOID                     1005
#define IDC_EDIT_BORNEID                1005
#define IDC_TEXT_DISPLAY                1006
#define IDC_LABEL_TYPEBORNE             1006
#define IDC_ZOBBY                       1007
#define IDC_LABEL_BORNEID               1007
#define IDC_LABEL_DB                    1008
#define IDC_LABEL_COUPLEUR              1009
#define IDC_LABEL7                      1010
#define IDC_COMBO_COUPLEUR_MODEL        1010
#define IDC_LABEL8                      1011
#define IDC_LABEL_COMPORT               1011
#define IDC_EDIT_READER_COMPORT         1013
#define IDC_FLECHEG                     1014
#define IDC_EDIT_SAMADDR                1014
#define IDC_FLECHED                     1015
#define IDC_LABEL_SAMADDR               1015
#define IDC_DEBUG_BTN                   1016
#define IDC_LABEL_LOG_READER            1016
#define IDC_COMBO_LOGREADER             1017
#define IDC_GROUPBOX_GNRAL              1018
#define IDC_PROP                        1019
#define IDC_GROUPBOX_COUPLEUR           1019
#define IDC_BANNER                      1020
#define IDC_CHECK1                      1057
#define IDC_VISIBLE                     1275
#define IDC_LISTBOXTEXT                 1336
#define IDC_LISTBOXINFO                 1360
#define IDC_TABORDERLABEL               1361
#define IDC_LISTITEMS                   1842
#define IDC_READONLY                    1963
#define IDC_LOADBMP_BTN                 1970
#define IDC_OPTIONSTREE_OPTIONS         1971
#define IDC_NAME                        1972
#define IDC_COMBO1                      1974
#define IDC_COMBO2                      1975
#define IDC_COMBO3                      1976
#define IDC_COMBO4                      1977
#define IDC_STATUS_BTN                  1978
#define ID_XUILITEHTML                  32761
#define ID_DYNBUTTONRADIO               32762
#define ID_XUIRADIO                     32762
#define ID_BORNE_DEMARRER               32763
#define ID_BUTTON32773                  32763
#define ID_DYNBUTTONDATE                32764
#define ID_XUIDATE                      32764
#define IDC_SETTINGS                    32765
#define ID_FULL_SCREEN_MODE             32766
#define ID_ADD_BUTTON                   32767
#define ID_ADD_EDIT                     32768
#define ID_ADD_STATIC                   32769
#define ID_DYNBUTTONEDITMULTI           32770
#define ID_XUIEDITMULTI                 32770
#define ID_ADD_CHECKBOX                 32771
#define ID_ADD_RADIOBUTTON              32772
#define ID_ADD_LISTBOX                  32773
#define ID_ADD_GROUPBOX                 32774
#define ID_ZOOM_IN                      32775
#define ID_ZOOM_OUT                     32800
#define ID_ADD_COMBOBOX                 32801
#define ID_SNAP_TO_GRID                 32802
#define ID_SHOW_GRID                    32804
#define ID_MARGINS                      32806
#define ID_RESTRAIN                     32807
#define ID_ADD_NONE                     32819
#define ID_BUTTON_MULTIDRAW             32821
#define ID_DYNBUTTONLABEL               32843
#define ID_XUILABEL                     32843
#define ID_DYNBUTTONCOMBO               32844
#define ID_XUICOMBO                     32844
#define ID_DYNBUTTONCHECK               32846
#define ID_XUICHECK                     32846
#define ID_DYNBUTTONGROUP               40001
#define ID_XUIGROUP                     40001
#define ID_DYNBUTTONLEFTALIGN           40003
#define ID_DYNBUTTONTOPALIGN            40005
#define ID_DYNBUTTONBOTTOMALIGN         40006
#define ID_DYNBUTTONMAKESAMEWIDTH       40010
#define ID_DYNBUTTONMAKESAMEHEIGHT      40011
#define ID_DYNBUTTONMAKESAMESIZE        40012
#define ID_DYNBUTTONRIGHTALIGN          40015
#define ID_XUIEDIT                      40016
#define ID_DYNBUTTONTOGGLEGRID          40017
#define ID_BORNE_STOP                   40018
#define ID_DYNBUTTONPICTURE             40019
#define ID_XUIPICTURE                   40019
#define CMD_START                       40020
#define ID_EDIT_OPTIONS                 40020
#define CMD_CUT                         40021
#define CMD_COPY                        40022
#define CMD_DUPLICATE                   40023
#define CMD_PROPERTIES                  40024
#define CMD_UP                          40025
#define CMD_DOWN                        40026
#define CMD_FRONT                       40026
#define CMD_BOTTOM                      40027
#define CMD_SELECT_GROUP                40028
#define CMD_END                         40029
#define ID_HOME_VIEW                    40030
#define ID_BORNE_VIEW                   40031
#define ID_SCREEN_DESIGNER              40032
#define ID_XUIFRAME                     40033

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        345
#define _APS_NEXT_COMMAND_VALUE         40034
#define _APS_NEXT_CONTROL_VALUE         1980
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
