/* Generated by Together */

#ifndef EPROPERTYDOUBLE_H
#define EPROPERTYDOUBLE_H

#include "EIconTextButtonProperty.h"

class EPropertyDouble : public EIconTextButtonProperty
{

public:

	//someone to ask about unitscale and symbol
	class UnitScaleHost
	{
	public:
		virtual double GetUnitScale( CString& sSymbol )
		{
			return 1.0;
		}
	};
	
private:

	UnitScaleHost* m_pUnitScaleHost;

	double  m_dMin;
	double  m_dMax;
	int     m_nNumDecimals;
	double  m_dScale;		//scale the property by this value before showing on screen (eg for showing value in another unit)
	CString m_sFixedUnit;
	const CString* m_pUnitSymbol;	//this holds pointer to the string holding the unit
	const double*  m_pScaleMul;		//this holds pointer to scale value
	const double*  m_pScaleDiv;		//this holds pointer to scale value

protected:

	double GetScale();				//mul/div
	virtual bool HasEdit();

public:

	virtual CString GetTextValue();
	virtual bool OnPropApply();

public:

    EPropertyDouble(  IPropertyHost* pHost , const CString& sName , double* pProperty , const CString& sUnit , double dMinAllowed=0 , double dMaxAllowed=0 , bool bEnabled=true );
	virtual ~EPropertyDouble();

	EPropertyDouble* SetStyle( UINT nFormatFlags=EIconTextButtonProperty::DEFAULT , int nNumDecimals=-1 );	//present value with thousand separator?
	EPropertyDouble* SetScale( double dScale );					//scale value for presentation? the value in your variable is scaled by this value, before showing on gui
	EPropertyDouble* SetUnit( const CString* pUnitSymbol );
	EPropertyDouble* SetScale( const double* pMultiply , const double* pDivide );
	EPropertyDouble* SetUnit( UnitScaleHost* pUnitScaleHost );

};

#endif //EPROPERTYDOUBLE_H