/* Generated by Together */

#ifndef EPROPERTYSTRING_H
#define EPROPERTYSTRING_H

#include "EIconTextButtonProperty.h"

class IPropertyHost;

class EPropertyString : public EIconTextButtonProperty
{

public:

	//
	// construction/destruction
	//
    EPropertyString( IPropertyHost* pHost , const CString& sName , CString* pProperty , bool bEnabled = true );
	~EPropertyString();

	//
	// EIconTextButtonProperty
	//
	virtual CString GetTextValue();
	virtual bool OnPropApply();

	//
	// this
	//
	virtual bool HasEdit();


};
#endif //EPROPERTYSTRING_H